# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

python: 3.7

# Install the codecov pip dependency
install:
  - pip install pytest pytest-cov

# Run the unit test
script:
  - python -m pytest --cov=./

# Push the results back to codecov
after_success:
  - codecov
